### ISSUE TITLE
Unknown interaction

### ISSUE THREAD

**Issue by brian-gates** [Adventure-Bot/adventure-bot#146]
```
command adventure
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/brian/adventure-bot/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RequestHandler.push (/home/brian/adventure-bot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at CommandInteraction.deferReply (/home/brian/adventure-bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:57:5)
    at Client.<anonymous> (/home/brian/adventure-bot/packages/game/src/boot.ts:99:7) {
  method: 'post',
  path: '/interactions/943668880830775376/aW50ZXJhY3Rpb246OTQzNjY4ODgwODMwNzc1Mzc2OnJ6SVk2TFRKZkh0QjZ6WVFmY1NKeHMwWWl4WU9ONEV5U0JpTU9jRTJDWk9nTnZvZW9CTElQbjJwMVp5aFZSdkNaUmhEVzRBTUgwYkltVWdOWGtYbWF6TE9wVmZRT3F2MjJLZHc2Y2MzdU1pbGExa3pJOVM2RGJ4Rjd2OVFxbXFI/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 5, data: [Object] }, files: [] }
}
```

**Comment by brian-gates** [comment]
It doesn't even work if I reduce it down to
```ts
  client.on('interactionCreate', async (interaction) => {
    if (!interaction.isCommand()) return
    await interaction.deferReply()
    interaction.editReply(`Test`)
  })
```

**Comment by brian-gates** [comment]
![image](https://user-images.githubusercontent.com/97096/154391206-6ad663d2-9f6c-47cc-86d6-36d3802cbd8b.png)

https://discord.com/channels/222078108977594368/824411059443204127/943678213882798080
